version: "3.8"

services:
  app: # OIDC Server
    image: nodeapp-dev
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DATABASE_URI: mongodb://db:27017
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
  db: # PostgreSQL
    image: mongo:4.4.3
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
