version: "3.8"

services:
  app: # OIDC Server
    image: nodeapp-dev
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    environment:
      # - "DEBUG=oidc-provider:*"
      - "DATABASE_URI=postgres://user:password@db:5432/mydatabase"
      - "NODE_ENV=development"
      - "ISSUER=http://localhost:3000"
      - "REDIS_URL=redis://redis:6379"
  db: # PostgreSQL
    image: postgres:13.2
    environment:
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=mydatabase"
    ports:
      - "5432:5432"
  redis: # Redis server
    image: redis:6.2.0-alpine
    ports:
      - "6379:6379"
