version: "3.8"

services:
  app: # OIDC Server
    image: nodeapp-dev
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    environment:
      # - "DEBUG=oidc-provider:*"
      - 'OIDCCONFIGURATION={"clients":[{"client_id":"myclient","client_secret":"secret","grant_types":["refresh_token","authorization_code"],"redirect_uris":["http://localhost:3001/callback"]},{"client_id":"myclient2","client_secret":"secret2","grant_types":["refresh_token","authorization_code"],"redirect_uris":["http://localhost:3002/callback"]}],"cookies":{"long":{"signed":true,"maxAge":86400000,"secure":false},"short":{"signed":true,"secure":false},"keys":["some secret key","and also the old rotated away some time ago","and one more"]}}'
      - 'JWKS={"keys":[{"crv":"P-256","x":"e5ueZN41eB6aFdFg6MLqgK8Dp64bntukUdJgEOxRHxo","y":"BaknNyqqPCY_UX2PbfIHxRyt61LA0CdLvIZnpCu40FM","d":"aXK7fcJ7-VZ74HCvtkZOZL8J41C-DiKkCpethq1yIhc","kty":"EC","kid":"-7u1phUMpt8sUlfkt13syi7Tnw-8CVMcrJEXaV7OjCo","alg":"ES256","use":"sig"},{"crv":"Ed25519","x":"bFhWrKpcfONtO5LnjRIUgTiTNz6lIhDmwEKB670KqhM","d":"S0nn2jdXJQFgjyXYRoipL1Zk4K35KEkcny_8qB_evIk","kty":"OKP","kid":"t0mEzesRSRMs_nZc5P05H96KEXG78fnvwP6TvMBRI7o","alg":"EdDSA","use":"sig"},{"e":"AQAB","n":"tAUwtGqsHw1RWQxREsZEbtcju25dWyl_MKbKIG4JMXIHIawQ-MZ1c8Igkv1O_z3aqsq00TUXgkjYN5-dF0jWOqp8jPRNV60DgtUl6zWChVyTTwzAEgQaJk1jjOrn7lPU6Y0U7OqeGSkiVlXNvKe1AGJHdZWhtZVexFz7zlNFP6mMI6wQCP3P9mHxFKMafq7GGkTpSk0JP11epgVlXrs8Y4VS-L71TM01t4N42_c_f57f9BbUlRJnsGdrL8MmJCRUhjIXNfG-zqaxViZLYR-bAH5y8b-6DvVkoE8ceSNkA-Kip0vU8-jeAdyfy3fQRn0Jd1mKAw7QM3Gvhh5Dl3ve3w","d":"bG6P5qw2HsIT1LJRhyB7idP2hug0PTvii7h7GUuOKAVJ_GM7Gc3YYzB0FHWVhrKIKsXMYhM7pNMhwWdX5PWPbGjSesiQaZYh_kVLAMELbC7V4BCLBI8J_TYyF2hK6Uf_f-nlx8qODhOzxhMKyG6v3JpV9qJ5c_mTym1DkwSfOndv9L5OlBiTsNJm2y99bXRca2loOM9Hu6ENDpdmxeMupYfsyxNcfE0HwMU3KGVbVGxZKikts3wlYSHBQHk5_O_Uj1dnbQ1g_Xlr9FvTlsbZWUXrhGI41jrqW-N4xE5mYtyPJFj29ztch7utvcShcSLh-hr06epHFHOxTHxm-gucEQ","p":"2polhFCwDFjR56WdK5kRtIkxMY8078Agr4EiVJwNw07KlA5YkKoVA8oMC-gswhCUYJDS7Dl7KmJaB_V5zz6-SZnVRJNMNszqD326_Q6TTYXO7KRAGTS6D_KUvgbh0GNYMl_8XR0bDIssgib90zqFi7hTH_mVM1l2j_tR52VRLGc","q":"0tFSEpabKK1NKhbD1TkDdoP4wu3h379lTW9l4ysP9yj1lvD847uvEfNmjUHXrrcwpU82B8fFH1_QbM4CA1w4WGZeCXodqvS-loLFikr7y0HeJ2rBLa_Twndo5g0yjyNBUaFoT4HBix5zOVS-_sef3rsvsR1ewgNRjU7gs3Gersk","dp":"lr2E8WDShTEaTaqeXtoGo3-XNJ2T21-ZKmzZx450zyEeAEqEN_2Q0DQbanqHoqrcJlq3l71reSao_qP_gzG49ffmYItSGtfi7xu8PZQ3b1W-AuCgcsExLJ4Sg5crUA-xWctmsq7HYDb4UiehEG9id557c6kfgXFHmLGtIOt0tjE","dq":"zAllOrJi50KbjWHNFaABlwHxkI_1bb1rST_Ix82UvSz6TKVezPaIYYJGve581g9c2JHKhEs3oL72FWhpEGF_8ybYWqnC7wPDNh7JG6io_Db60QGEiDhFZlB1yTn6tgh0HpJuR40ZChFliZZY6HPCaiqW5P-9B1943Z_64BHWd-k","qi":"1gUS3QWSjS7asCq1hiSebhPikIiUv8j6RPBSzDIc7h90GPx11oYtZ_Y2OaknL_bndFpqLFbew_ey1unZuefawim2SnXnUkLWiixiUqPEM6sh3BCnIz_mnHTqxAk0X44VKFGY6l-EEo8_Rhl8o7rmUvpnVqnGKldo5UR2SMQfsvo","kty":"RSA","kid":"k4GOjmm09k4rrba6wHy9MbS1No6HwFPOo0udI1N2FtM","use":"sig"}]}'
      - "DATABASE_URI=postgres://user:password@db:5432/mydatabase"
      - "NODE_ENV=development"
      - "ISSUER=http://localhost:3000"
      - "REDIS_URL=redis://redis:6379"
  db: # PostgreSQL
    image: postgres:13.2
    environment:
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=mydatabase"
    ports:
      - "5432:5432"
  redis: # Redis server
    image: redis:6.2.0-alpine
    ports:
      - "6379:6379"
