name: Publish Docker image (Development)
on:
  push:
    branches:
      - development
jobs:
  buildx:
    name: build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_IMAGE_TAG_NAME }}:dev

      - name: Image digest
        run: |
          echo IMAGE NAME: ${{ secrets.DOCKER_IMAGE_TAG_NAME }}:dev
          echo DIGEST: ${{ steps.docker_build.outputs.digest }}
